//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPrice
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int ActivityId { get; set; }
        public int ActivityPriceTypeId { get; set; }
        public int PassengerAmount { get; set; }
        public int Price { get; set; }
        public int PriceNet { get; set; }
        public string Comments { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivityPriceType ActivityPriceType { get; set; }
    }
}
