//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderRequests()
        {
            this.OrderActivityData = new HashSet<OrderActivityData>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> NumberOfPassengers { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<bool> FromAirportTransferUsed { get; set; }
        public Nullable<bool> FromHotelTransferUsed { get; set; }
        public Nullable<bool> DayUse { get; set; }
        public Nullable<int> Nights { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string ArriveFlight { get; set; }
        public string DepartureFlight { get; set; }
        public string Routes { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderActivityData> OrderActivityData { get; set; }
    }
}
