//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCost
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int OrderId { get; set; }
        public Nullable<decimal> AirfareTaxes { get; set; }
        public Nullable<decimal> FirstNightPackageCost { get; set; }
        public Nullable<decimal> RestNightGross { get; set; }
        public Nullable<decimal> ToursGross { get; set; }
        public Nullable<decimal> TotalExpenseFirstNight { get; set; }
        public Nullable<decimal> TotalExpenseTransfer { get; set; }
        public Nullable<decimal> RestNightNet { get; set; }
        public Nullable<decimal> TursNet { get; set; }
        public Nullable<decimal> OneDollarExpense { get; set; }
        public Nullable<decimal> SalesCommission { get; set; }
        public Nullable<decimal> ORCCommission { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> KCRevenue { get; set; }
        public Nullable<decimal> PercentFromTicketPrice { get; set; }
        public string Content { get; set; }
        public string Comments { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
