//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderActivity()
        {
            this.ActivityPassenger = new HashSet<ActivityPassenger>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int OrderId { get; set; }
        public int ActivityTimeId { get; set; }
        public int ActivityId { get; set; }
        public System.DateTime Date { get; set; }
        public string TransferLocation { get; set; }
        public int Price { get; set; }
        public string Comments { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityPassenger> ActivityPassenger { get; set; }
        public virtual ActivityTime ActivityTime { get; set; }
        public virtual Order Order { get; set; }
    }
}
