//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderStopoverData
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        [Display(Name = "Room Type")]
        public Nullable<int> RoomTypeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Display(Name = "Child")]
        public Nullable<bool> IsChild { get; set; }
        [Display(Name = "PNR")]
        public string BookingReference { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> RoomNum { get; set; }
    }
}
