//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderRequests()
        {
            this.OrderActivityData = new HashSet<OrderActivityData>();
            this.OrderStopoverData = new HashSet<OrderStopoverData>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<int> RequestStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderActivityData> OrderActivityData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStopoverData> OrderStopoverData { get; set; }
    }
}
