//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderActivityData
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        [Display(Name = "City")]
        public Nullable<int> CityId { get; set; }
        [Display(Name = "Activity")]
        public Nullable<int> ActivityId { get; set; }
        [Display(Name = "Activity Time")]
        public Nullable<int> ActivityTimeId { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string TransferLocation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsChild { get; set; }
    
        public virtual OrderRequests OrderRequests { get; set; }
    }
}
