//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopoverAdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int OrderId { get; set; }
        public string Reference { get; set; }
        public int TotalPrice { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string ReferralPayment { get; set; }
        public string EMD { get; set; }
        public string Comments { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
